import type { Language, ThemePreference, UserPreferences } from '../types/domain';
import type { CopyKey } from '../i18n';

interface SettingsPageProps { preferences: UserPreferences; labels: Record<CopyKey, string>; onLanguage(language: Language): void; onTheme(theme: ThemePreference): void; }

export function SettingsPage({ preferences, labels, onLanguage, onTheme }: SettingsPageProps) {
  return <div className="page simple-page settings-page">
    <header className="page-heading compact-heading"><div><p className="eyebrow">Make it yours</p><h1>{labels.settings}</h1><p>Locale, planning boundaries, notifications and provider connections.</p></div></header>
    <div className="settings-layout"><nav className="settings-nav"><button className="active" type="button">General</button><button type="button">Planning</button><button type="button">Notifications</button><button type="button">Connections</button></nav><section className="content-panel settings-panel">
      <div className="setting-group"><header><h2>General</h2><p>Language selection also changes the calendar system.</p></header><label className="setting-row"><span><strong>{labels.language}</strong><small>English uses Gregorian (AD); Nepali uses Bikram Sambat (BS).</small></span><select value={preferences.language} onChange={(event) => onLanguage(event.target.value as Language)}><option value="en">English · Gregorian</option><option value="ne">नेपाली · विक्रम संवत्</option></select></label><label className="setting-row"><span><strong>Time zone</strong><small>Used for all scheduling and conflict checks.</small></span><input value={preferences.timezone} readOnly /></label><label className="setting-row"><span><strong>{labels.theme}</strong><small>Choose light, dark or follow your device.</small></span><select value={preferences.theme} onChange={(event) => onTheme(event.target.value as ThemePreference)}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label></div>
      <div className="setting-group"><header><h2>Planning boundaries</h2><p>The planner respects these limits before suggesting time.</p></header><div className="setting-row"><span><strong>Work hours</strong><small>{preferences.workingDays.length} working days</small></span><b>{preferences.workDayStart} – {preferences.workDayEnd}</b></div><div className="setting-row"><span><strong>Sleep hours</strong><small>Protected by default</small></span><b>{preferences.sleepStart} – {preferences.sleepEnd}</b></div><div className="setting-row"><span><strong>Default durations</strong><small>Event · Task</small></span><b>{preferences.defaultEventMinutes}m · {preferences.defaultTaskMinutes}m</b></div></div>
      <div className="setting-group"><header><h2>Connections</h2><p>Adapters are defined; credentials are intentionally not stored in the client.</p></header><div className="provider-row"><span className="provider-logo">G</span><span><strong>Google Calendar</strong><small>Import, export and two-way sync adapter</small></span><b>Not connected</b></div><div className="provider-row"><span className="provider-logo">O</span><span><strong>Microsoft Outlook</strong><small>OAuth provider configuration required</small></span><b>Not connected</b></div><div className="provider-row"><span className="provider-logo">A</span><span><strong>Apple Calendar</strong><small>ICS import/export adapter planned</small></span><b>Not connected</b></div></div>
    </section></div>
  </div>;
}
